import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/mycontext";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { DataProvider } from "./context/datacontext";
import { RecordProvider } from "./context/addRecord-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <DataProvider>
            <RecordProvider>{children}</RecordProvider>
            <ToastContainer />
          </DataProvider>
        </UserProvider>
      </body>
    </html>
  );
}
